### ISSUE TITLE
a small bug in tdavg

### ISSUE THREAD

**Issue by archion** [rokzitko/nrgljubljana#5]
don't have any c++ coding experience but I think
https://github.com/rokzitko/nrgljubljana/blob/59d30dcfb30f52aa37becc7f5b3628513ab5c4a7/tools/tdavg/tdavg.cc#L93
should be like
```
    ref_name = string(argv[optind+1]); // Reference filename
```

**Comment by rokzitko** [comment]
Yes, absolutely, you are right. Thank you!
I'll fix it.
